# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskdish',
            name='dish_num',
            field=models.IntegerField(default=1, verbose_name='菜品数量'),
        ),
    ]
