# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_center', '0002_auto_20180921_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskdish',
            name='is_served',
            field=models.IntegerField(choices=[(1, '已经上菜'), (0, '没有上菜')], default=0, verbose_name='是否已上菜'),
        ),
    ]
