# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-21 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_center', '0003_auto_20180921_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskdish',
            name='is_served',
            field=models.BooleanField(default=False, verbose_name='是否已上菜'),
        ),
    ]
