# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_center', '0004_auto_20180921_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_finished',
            field=models.BooleanField(default=False, verbose_name='是否完成订单'),
        ),
    ]
